 CREATE TABLE 'thomkevi-db'.'VIDEO_INVENTORY' (
'ID' INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
'NAME' VARCHAR( 255 ) NOT NULL ,
'CATEGORY' VARCHAR( 255 ) NULL ,
'LENGTH' INT NULL ,
'RENTED' BOOL NOT NULL DEFAULT '0',
UNIQUE (
'NAME'
)
) ENGINE = MYISAM 